package com.gpstracker.server.api.core;

import com.gpstracker.server.core.model.CallbackProcessingResult;

/**
 * The call back response store is used to hold responses that have been generated by asynchronous processing. 
 * An implement of the store should allow stored objects to be accessible from any running instance of the
 * application. 
 */
public interface CallbackResultStore {
    
    /**
     * Stores a call back response.
     * 
     * @param processingResult the callback response to store
     * @return true if the result was stored, false otherwise
     */
    boolean store(final CallbackProcessingResult processingResult);
    
    /**
     * Gets retrieves a callback response.
     * 
     * @param id the identifier of the callback response to retieve
     * @return the callback response object, may return null
     */
    CallbackProcessingResult get(final String id);
}
